server:
  port: 8080

spring:
  application:
    name: url-shortening-service
  datasource:
    url: jdbc:postgresql://localhost:5432/shortening_service
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false