version: '3.8'

services:
  postgre_db:
    image: postgres:16-alpine
    container_name: postgre_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gatekeeper
      POSTGRES_USERNAME: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: