spring:
  application:
    name: gatekeeper
  datasource:
    url: jdbc:postgresql://localhost:5432/gatekeeper
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-minutes: 900000